spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      generate_statistics: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 1688bd590ef962
    password: 34260b646214ca

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

server:
  port: 8001
