global:
  scrape_interval: 20s
  scrape_timeout: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node_exporter
    static_configs:
      - targets:
          - host.docker.internal:9100

  - job_name: infrastructure
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8084