
create table infra_image
(
    id       bigint generated by default as identity
        primary key,
    frame    integer,
    path_url varchar(255)
);

alter table infra_image
    owner to admin;

create table fake_event
(
    id         varchar(255)     not null
        primary key,
    category   varchar(255),
    confidence double precision not null,
    latitude   double precision not null,
    location   varchar(255),
    longitude  double precision not null,
    name       varchar(255),
    status     varchar(255),
    time       timestamp(6),
    image_id   bigint
        constraint fkmv85cnctibu7sddy2ansokx26
            references infra_image
);

alter table fake_event
    owner to admin;

create table infra_info
(
    id              bigint generated by default as identity
        primary key,
    additional_data varchar(255),
    avatar          varchar(255),
    create_at       timestamp(6),
    key_id          varchar(255),
    manage_unit     varchar(255),
    original_image  varchar(255)
);

alter table infra_info
    owner to admin;

create table infra_objects
(
    id            varchar(255)     not null
        primary key,
    bbox          varchar(255),
    camera_id     varchar(255),
    category      varchar(255),
    confidence    double precision not null,
    date_captured timestamp(6),
    geography     geography(Point, 4326),
    is_updated    boolean,
    latitude      double precision,
    level         integer,
    location      varchar(255),
    longitude     double precision,
    name          varchar(255),
    real_height   double precision,
    real_width    double precision,
    schedule_id   varchar(255),
    status        varchar(255),
    type          varchar(255)
        constraint infra_objects_type_check
            check ((type)::text = ANY
                   ((ARRAY ['ASSET'::character varying, 'ABNORMALITY'::character varying])::text[])),
    image_id      bigint
        constraint fkl5csrylihhemlh2tk07g8kglq
            references infra_image,
    info_id       bigint
        constraint uk8coo994rah30kgy4s7ixb7wmp
            unique
        constraint fkavwe12j0jtscbu8p0u1fijymk
            references infra_info
);

alter table infra_objects
    owner to admin;

create table history
(
    id              bigint generated by default as identity
        primary key,
    bbox            varchar(255),
    confidence      double precision not null,
    date_captured   timestamp(6),
    level           integer,
    real_height     double precision,
    real_width      double precision,
    schedule_id     varchar(255),
    status          varchar(255),
    image_id        bigint
        constraint fkbtjl1kfgulbpi8raif8okjegx
            references infra_image,
    infra_object_id varchar(255)
        constraint fk21npyh6gyd6tg5ai7crrw5swh
            references infra_objects
);

alter table history
    owner to admin;

create table process_ticket
(
    id            bigint generated by default as identity
        primary key,
    assigned_to   varchar(255),
    created_at    timestamp(6),
    description   varchar(255),
    level         integer,
    ticket_status varchar(255)
        constraint process_ticket_ticket_status_check
            check ((ticket_status)::text = ANY
                   ((ARRAY ['NEW'::character varying, 'UPDATED'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])),
    title         varchar(255),
    updated_at    timestamp(6)
);

alter table process_ticket
    owner to admin;

create table event
(
    id              varchar(255)     not null
        primary key,
    bbox            varchar(255),
    confidence      double precision not null,
    date_captured   timestamp(6),
    end_time        timestamp(6),
    event_status    varchar(255),
    level           integer,
    real_height     double precision,
    real_width      double precision,
    schedule_id     varchar(255),
    status          varchar(255),
    event_ticket_id bigint
        constraint uk6lku9nrva2eraxb1oaej7prqk
            unique
        constraint fksuwr2x38y9seg1pf7wa2q6esw
            references process_ticket,
    image_id        bigint
        constraint fkq0oj6156uqyhyulf0x2fj6a3a
            references infra_image,
    infra_object_id varchar(255)
        constraint fkatftofxuy5phi3gjr5lt9u2aq
            references infra_objects
);

alter table event
    owner to admin;

create table infra_object_process
(
    id                varchar(255) not null
        primary key,
    bbox              varchar(255),
    camera_id         varchar(255),
    category          varchar(255),
    confidence        double precision,
    date_captured     timestamp(6),
    event_status      varchar(255)
        constraint infra_object_process_event_status_check
            check ((event_status)::text = ANY
                   ((ARRAY ['NEW'::character varying, 'UPDATED'::character varying, 'FAKE'::character varying, 'REPAIR'::character varying, 'FINISHED'::character varying, 'LOST'::character varying, 'CREATED'::character varying])::text[])),
    key_id            varchar(255),
    latitude          double precision,
    level             integer,
    location          varchar(255),
    longitude         double precision,
    name              varchar(255),
    process_status    varchar(255)
        constraint infra_object_process_process_status_check
            check ((process_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])),
    real_height       double precision,
    real_width        double precision,
    schedule_id       varchar(255),
    status            varchar(255),
    type              varchar(255)
        constraint infra_object_process_type_check
            check ((type)::text = ANY
                   ((ARRAY ['ASSET'::character varying, 'ABNORMALITY'::character varying])::text[])),
    image_id          bigint
        constraint fk1bkpiulwregr0cl6139s4xu96
            references infra_image,
    infra_object_id   varchar(255)
        constraint fkpkchs5gfku6n6wicpmsaanyih
            references infra_objects,
    process_ticket_id bigint
        constraint ukjn9v3kf61c6jfqma46ds1jnyf
            unique
        constraint fkalqdx1q1iefmg0o7n4wyoy6b
            references process_ticket
);

alter table infra_object_process
    owner to admin;

create extension if not exists unaccent;
CREATE INDEX if not exists idx_infra_location ON infra_objects USING GIST (geography);